In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
import cloudinary
import cloudinary.uploader as uploader
from bs4 import BeautifulSoup
import requests
import base64

In [3]:
cloudinary.config(
  cloud_name = "hmvh5jw7x",
  api_key = "355912947378767",
  api_secret = "EzVcH3FXVuRQh3eZjbvjWcqXEZg"
)

In [11]:
df = pd.read_csv("apps.csv",encoding='latin1')

In [12]:
df.head()

       Brand       Category          Notes     Country Wiki  Image
0     TikTok  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
1       KWAI  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
2       Helo  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
3      Likee  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
4  Bigo Live  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN

In [13]:
df

          Brand       Category          Notes     Country Wiki  Image
0        TikTok  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
1          KWAI  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
2          Helo  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
3         Likee  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
4     Bigo Live  Video-Sharing  Video-Sharing  Non-Indian  NaN    NaN
...         ...            ...            ...         ...  ...    ...
1553        NaN            NaN            NaN         NaN  NaN    NaN
1554        NaN            NaN            NaN         NaN  NaN    NaN
1555        NaN            NaN            NaN         NaN  NaN    NaN
1556        NaN            NaN            NaN         NaN  NaN    NaN
1557        NaN            NaN            NaN         NaN  NaN    NaN

[1558 rows x 6 columns]

In [14]:
df["Image"] = df["Image"].fillna('')

In [15]:
def scrapImage(name):
    fName = name.replace(" ","").replace("&","").replace("?","").replace("-","").replace(".","").replace("\n","").replace(";","")
    name = name.split()
    name.append("logo")
    link = "https://www.google.com/search?q={}&tbm=isch".format('+'.join(name))
    r=requests.get(link)
    soup=BeautifulSoup(r.content,'html.parser')
    try:

        mainSoup = soup.find_all("table",{"class":"GpQGbf"})[0]
        images = mainSoup.find_all("img")
        link = images[0].get('src')
    except Exception as E:
        print(E)
        print(fName)
        return None
    img = requests.get(link)
    image = img.content
    image = uploader.upload_resource(image, folder="Vocal4Local/{}".format(fName))
    return image.metadata["secure_url"]

In [17]:
for i in df.iterrows():
    try:
        name = i[1]["Brand"]
        if i[1]["Image"]:
            continue
        image = scrapImage(name)
        print(i[0],name,image)
        df.at[i[0], 'Image'] = image
    except Exception as E:
        print(E)

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'

In [36]:
# x = x.split(';base64,')[1]
# x = base64.b64decode(x)

In [18]:
df.head()

,Brand,Category,Notes,Country,Wiki,Image
0,TikTok,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,KWAI,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Helo,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Likee,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Bigo Live,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...

In [19]:
df

,Brand,Category,Notes,Country,Wiki,Image
0,TikTok,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,KWAI,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Helo,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Likee,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Bigo Live,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
...,...,...,...,...,...,...
1553,NaN,NaN,NaN,NaN,NaN,
1554,NaN,NaN,NaN,NaN,NaN,
1555,NaN,NaN,NaN,NaN,NaN,
1556,NaN,NaN,NaN,NaN,NaN,
1557,NaN,NaN,NaN,NaN,NaN,

In [20]:
df.to_csv("appsWithImages.csv",index=False)

In [14]:
# df = pd.read_csv("res.csv")

In [21]:
df.head()

,Brand,Category,Notes,Country,Wiki,Image
0,TikTok,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,KWAI,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Helo,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Likee,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Bigo Live,Video-Sharing,Video-Sharing,Non-Indian,NaN,https://res.cloudinary.com/hmvh5jw7x/image/upl...

In [22]:
df["Wiki"] = df["Wiki"].fillna(0)

In [42]:
# df["Wiki"] = None

In [23]:
for i in df.iterrows():
    if i[1]["Wiki"] or i[1]["Country"] not in ["India","Indian"]:
        continue
    name = i[1]["Brand"]
    name = name.split()
    name.append("Brand")
    name.append("wiki")
    link = "https://www.google.com/search?q={}".format('+'.join(name))
    r=requests.get(link)
    soup=BeautifulSoup(r.content,'html.parser')
    myDiv = soup.find_all("div",{"class":"BNeawe s3v9rd AP7Wnd"})
    wiki = myDiv[0].text.split('...')[0]
    wiki = wiki.split('.')
    if len(wiki)>1:
        wiki.pop()
    wiki = '.'.join(wiki)
    wiki+="."
    wiki = wiki.split("Contents")[0]
    wiki = wiki.split("\n")[0]
    print(i[0],i[1]["Brand"]," - ", wiki)
    df.at[i[0],"Wiki"] = wiki

17 Jio Browser  -  Reliance Jio Infocomm Limited, d/b/a Jio, is an Indian telecommunications company and .
18 Bharat Browser  -  Marc Andreessen, the leader of the Mosaic team, soon started his own company, Netscape, which released the Mosaic-influenced Netscape Navigator in 1994.
21 Myntra  -  Myntra is an Indian fashion e-commerce company headquartered in Bengaluru, Karnataka, India.
22 Flipkart  -  Flipkart is an Indian e-commerce company based in Bangalore, Karnataka, India.
23 Snapdeal  -  Snapdeal, is an Indian e-commerce company based in New Delhi, India. The company was founded by Kunal Bahl and Rohit Bansal in February 2010.
24 AJIO  -  .
28 Indian Selfie Camera  -  A selfie is a self-portrait digital photograph, typically taken with a digital camera or smartphone, which may be held in the hand or supported by a selfie stick.
30 K7 Total Security  -  K7 Computing[edit]. K7 Computing Pvt. Ltd. is a software and hardware security company founded in 1991 by Jayaraman Kesavardhanan in Chennai, India.
32 Hike Messenger  -  Hike Messenger, also called Hike Sticker Chat, is an Indian freeware, cross- platform instant .
34 KaagazÂ Scanner  -  An image scannerâ€”often abbreviated to just scanner, is a device that optically scans images, .

In [24]:
df

,Brand,Category,Notes,Country,Wiki,Image
0,TikTok,Video-Sharing,Video-Sharing,Non-Indian,0,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,KWAI,Video-Sharing,Video-Sharing,Non-Indian,0,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Helo,Video-Sharing,Video-Sharing,Non-Indian,0,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Likee,Video-Sharing,Video-Sharing,Non-Indian,0,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Bigo Live,Video-Sharing,Video-Sharing,Non-Indian,0,https://res.cloudinary.com/hmvh5jw7x/image/upl...
...,...,...,...,...,...,...
1553,NaN,NaN,NaN,NaN,0,
1554,NaN,NaN,NaN,NaN,0,
1555,NaN,NaN,NaN,NaN,0,
1556,NaN,NaN,NaN,NaN,0,
1557,NaN,NaN,NaN,NaN,0,

In [25]:
df[df["Country"] == "India"]

,Brand,Category,Notes,Country,Wiki,Image
7,Chingari,Video-Sharing,Video-Sharing,India,"Chingari is a short video app like TikTok, ava...",https://res.cloudinary.com/hmvh5jw7x/image/upl...
8,Roposo,Video-Sharing,Video-Sharing,India,This Indian content sharing and video creation...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
12,Shareall,File Sharing,File Sharing,India,Shareall is an Android file sharing applicatio...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
13,Z Share,File Sharing,File Sharing,India,"Developed by Shravan Hegde from Dharwad, Karna...",https://res.cloudinary.com/hmvh5jw7x/image/upl...
17,Jio Browser,Web Browser,Web Browser,India,"Reliance Jio Infocomm Limited, d/b/a Jio, is a...",https://res.cloudinary.com/hmvh5jw7x/image/upl...
18,Bharat Browser,Web Browser,Web Browser,India,"Marc Andreessen, the leader of the Mosaic team...",https://res.cloudinary.com/hmvh5jw7x/image/upl...
21,Myntra,E-commerce,E-commerce,India,Myntra is an Indian fashion e-commerce company...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
22,Flipkart,E-commerce,E-commerce,India,Flipkart is an Indian e-commerce company based...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
23,Snapdeal,E-commerce,E-commerce,India,"Snapdeal, is an Indian e-commerce company base...",https://res.cloudinary.com/hmvh5jw7x/image/upl...
24,AJIO,E-commerce,E-commerce,India,.,https://res.cloudinary.com/hmvh5jw7x/image/upl...
28,Indian Selfie Camera,Picture Editing,Picture Editing,India,A selfie is a self-portrait digital photograph...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
30,K7 Total Security,Virus Cleaner,Virus Cleaner,India,K7 Computing[edit]. K7 Computing Pvt. Ltd. is ...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
32,Hike Messenger,Messenger,Messenger,India,"Hike Messenger, also called Hike Sticker Chat,...",https://res.cloudinary.com/hmvh5jw7x/image/upl...
34,KaagazÂ Scanner,Photo Scanner,Photo Scanner,India,An image scannerâ€”often abbreviated to just sca...,https://res.cloudinary.com/hmvh5jw7x/image/upl...

In [26]:
df["Wiki"] = df["Wiki"].replace([0,"0"],"")

In [27]:
df

,Brand,Category,Notes,Country,Wiki,Image
0,TikTok,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,KWAI,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Helo,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Likee,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Bigo Live,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
...,...,...,...,...,...,...
1553,NaN,NaN,NaN,NaN,,
1554,NaN,NaN,NaN,NaN,,
1555,NaN,NaN,NaN,NaN,,
1556,NaN,NaN,NaN,NaN,,
1557,NaN,NaN,NaN,NaN,,

In [28]:
df["Notes"] = df["Notes"].fillna("")

In [29]:
df[df["Notes"] == ""]

     Brand Category Notes Country Wiki Image
35     NaN      NaN           NaN
36     NaN      NaN           NaN
37     NaN      NaN           NaN
38     NaN      NaN           NaN
39     NaN      NaN           NaN
...    ...      ...   ...     ...  ...   ...
1553   NaN      NaN           NaN
1554   NaN      NaN           NaN
1555   NaN      NaN           NaN
1556   NaN      NaN           NaN
1557   NaN      NaN           NaN

[1523 rows x 6 columns]

In [30]:
for i in df.iterrows():
    if i[1]["Notes"]=="":
        df.at[i[0],"Notes"] = i[1]["Category"]

In [31]:
df

,Brand,Category,Notes,Country,Wiki,Image
0,TikTok,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,KWAI,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Helo,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Likee,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Bigo Live,Video-Sharing,Video-Sharing,Non-Indian,,https://res.cloudinary.com/hmvh5jw7x/image/upl...
...,...,...,...,...,...,...
1553,NaN,NaN,NaN,NaN,,
1554,NaN,NaN,NaN,NaN,,
1555,NaN,NaN,NaN,NaN,,
1556,NaN,NaN,NaN,NaN,,
1557,NaN,NaN,NaN,NaN,,

In [32]:
df.to_csv("apps.csv",index=False)

In [10]:
df = pd.read_csv("finaldup.csv")

In [13]:
df

,Brand,Category,Notes,Country,Wiki,Image
0,Priya Gold,food oil,"Biscuits, Food Oil",India,Priya Gold is the ace brand of the Surya Food ...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,Air Odisha,Airlines,Charter airline,India,Air Odisha was an Indian regional airline base...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Air India,Airlines,Airline,India,Air India is the flag carrier airline of India...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Air India Express,Airlines,"Low-cost airline, part of Air India",India,Air India Express is an Indian low-cost airlin...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Deccan Charters,Airlines,Charter airline,India,Deccan Charters is an aviation company based i...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
...,...,...,...,...,...,...
1698,Dabur,NaN,NaN,India,Dabur (derived from Daktar Burman) is an India...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1699,Dukes,NaN,"Toffees, Biscuits",India,Dukes is an Indian food-products corporation a...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1700,KKW Beauty,Cosmetics,Skin Care,NaN,NaN,NaN
1701,KKW Fragnance,Cosmetics,Perfumes,NaN,NaN,NaN
1702,Biotique,Cosmetics,"Skin Care, Hair Products, Perfumes",NaN,NaN,NaN

In [12]:
for i in df.iterrows():
    name = i[1]["Brand"].strip()
    name = re.sub('\(.*\)', '', name).strip()
    df.at[i[0], "Brand"] = name

In [14]:
res = df.drop_duplicates(subset='Brand', keep="first").reset_index(drop=True)

In [15]:
res

,Brand,Category,Notes,Country,Wiki,Image
0,Priya Gold,food oil,"Biscuits, Food Oil",India,Priya Gold is the ace brand of the Surya Food ...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1,Air Odisha,Airlines,Charter airline,India,Air Odisha was an Indian regional airline base...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
2,Air India,Airlines,Airline,India,Air India is the flag carrier airline of India...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
3,Air India Express,Airlines,"Low-cost airline, part of Air India",India,Air India Express is an Indian low-cost airlin...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
4,Deccan Charters,Airlines,Charter airline,India,Deccan Charters is an aviation company based i...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
...,...,...,...,...,...,...
1690,Dabur,NaN,NaN,India,Dabur (derived from Daktar Burman) is an India...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1691,Dukes,NaN,"Toffees, Biscuits",India,Dukes is an Indian food-products corporation a...,https://res.cloudinary.com/hmvh5jw7x/image/upl...
1692,KKW Beauty,Cosmetics,Skin Care,NaN,NaN,NaN
1693,KKW Fragnance,Cosmetics,Perfumes,NaN,NaN,NaN
1694,Biotique,Cosmetics,"Skin Care, Hair Products, Perfumes",NaN,NaN,NaN

In [16]:
res.to_csv("final.csv",index=False)